### ISSUE TITLE
https://en.cppreference.com/w/c/program/EXIT_status

### ISSUE THREAD

**Issue by StepanTheFlowey** [ambr0siaa/LunaVM#14]
https://github.com/ambr0siaa/LunaVM/blob/850ce755c86638f24e8979e8c5e4bb4cbf015980/luna/src/luna.c#L56

**Comment by ambr0siaa** [comment]
Oh... I just have cathartic

**Comment by StepanTheFlowey** [comment]
will create pull request with all proposes
