### ISSUE TITLE
[HIGH PRIORITY] SECURITY VULNERABILITY (CVE-FUCK-001)

### ISSUE THREAD

**Issue by StepanTheFlowey** [ambr0siaa/LunaVM#16]
https://github.com/ambr0siaa/LunaVM/blob/850ce755c86638f24e8979e8c5e4bb4cbf015980/common/ht.h#L28

MD5?
did you hear about openssl?

sudo apt install -y libssl-dev openssl

i think by using openssl your code will be much more secure

**Comment by ambr0siaa** [comment]
no
