### ISSUE TITLE
CCFLAGS

### ISSUE THREAD

**Issue by StepanTheFlowey** [ambr0siaa/LunaVM#17]
https://github.com/ambr0siaa/LunaVM/blob/850ce755c86638f24e8979e8c5e4bb4cbf015980/bilSetup.sh#L8

use -fno-pic -fno-pie -no-pie gcc flags when compilling executables to reduce their size and improve performance and also to create vulnerability...

https://en.wikipedia.org/wiki/Position-independent_code

**Comment by ambr0siaa** [comment]
ok, thank you
